# instance_url should be Plextrac instance URL i.e. https://example.plextrac.com
instance_url: 
username: 
password: 

api_version: 

acunetic360_data_folder_path: files_to_process

# name of a report template in the Plextrac instance will be added to all reports
report_template_name: 
# name of a finding layout in the Plextrac instance will be added to all reports
findings_layout_name: 
